{% set name = "eth-rlp" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5b408a8cd20ed496e8e66d0559560d29bc21cee482f893936a1f05d0dddc4a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - setuptools-markdown
  run:
    - python >=3.8,<4.0
    - eth-utils >=2.0.0
    - hexbytes >=1.2.0
    - rlp >=0.6.0
    - typing_extensions >=4.0.1  # py<=3.10

test:
  imports:
    - eth_rlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-rlp
  summary: 'eth-rlp: RLP definitions for common Ethereum objects in Python'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
