{% set name = "eth-rlp" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70116ec32abd2569fc4ba5f2af80080d896b0dc53a86d582fe1ffa66ecfee308

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - setuptools-markdown
  run:
    - python >=3.8,<4.0
    - eth-utils >=2.0.0
    - hexbytes >=0.1.0,<1
    - rlp >=0.6.0
    - typing_extensions >=4.0.1  # py<=3.11

test:
  imports:
    - eth_rlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-rlp
  summary: 'eth-rlp: RLP definitions for common Ethereum objects in Python'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
