schema_version: 1

context:
  name: eth-rlp
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 9663e54a4a1c1c847d2d328c1d07e4174ec1c082953fbb42b60e61c501c4931c

build:
  number: 0
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content:
      - ${{ PYTHON }} -m pip install . -vv
      - if: unix
        then: rm -rf $SP_DIR/docs
      - if: win
        then: rmdir /s /q %SP_DIR%\docs

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
    - setuptools-markdown
  run:
    - python >=${{ python_min }},<4.0
    - eth-utils >=2.0.0
    - hexbytes >=1.2.0
    - rlp >=0.6.0
    - typing_extensions >=4.0.1  # py<=3.10

tests:
  - python:
      imports:
        - eth_rlp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"


about:
  summary: "eth-rlp: RLP definitions for common Ethereum objects in Python"
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ethereum/eth-rlp

extra:
  recipe-maintainers:
    - step21

